export const USERS_TYPES = {
	GET_ALL_STAFF: 'GET_ALL_STAFF',
	GET_ALL_ROLES: 'GET_ALL_ROLES',
	GET_ONE_USER: 'GET_ONE_USER',
	ADD_USER: 'ADD_USER',
	EDIT_USER: 'EDIT_USER',
	TOGGLE_USER_STATUS: 'TOGGLE_USER_STATUS',
	DELETE_USER: 'DELETE_USER',
};
